name: Static Site CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Render
      run: |
        echo "Deploying static files..."
        curl -fsSL https://render.com/deploy.sh | bash

    - name: Clean up
      run: |
        echo "CI/CD pipline completed."
        